spring.application.name=horticontrol

# Configurações H2
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:horticontroldb
spring.datasource.username=admin
spring.datasource.password=

# Dialeto do Hibernate para H2
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Console H2 (acessível em http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
