# === DATASOURCE DEV ===
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/horticontrol
spring.datasource.username=root
spring.datasource.password=root1234

# === LOGS ===
spring.jpa.show-sql=true

# === SWAGGER (somente DEV) ===
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# === JWT DEV ===
jwt.secret=c2VjcmV0LWNoYXZlLXNlZ3VyYS1ob3J0aWNvbnRyb2wtMjAyNg==
